=== valanths1990/l2j-server-datapack/src/main/resources/data/autobots/armorset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipment" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="classId" type="xs:string"/>
                                <xs:attribute name="grade">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="NONE"/>
                                            <xs:enumeration value="D"/>
                                            <xs:enumeration value="C"/>
                                            <xs:enumeration value="B"/>
                                            <xs:enumeration value="A"/>
                                            <xs:enumeration value="S"/>
                                            <xs:enumeration value="S80"/>
                                            <xs:enumeration value="S84"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="setId" type="xs:positiveInteger" default="1"/>
                                <xs:attribute name="weaponType" type="xs:string">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="SWORD"/>
                                            <xs:enumeration value="BLUNT"/>
                                            <xs:enumeration value="DAGGER"/>
                                            <xs:enumeration value="BOW"/>
                                            <xs:enumeration value="POLE"/>
                                            <xs:enumeration value="NONE"/>
                                            <xs:enumeration value="DUAL"/>
                                            <xs:enumeration value="ETC"/>
                                            <xs:enumeration value="FIST"/>
                                            <xs:enumeration value="DUALFIST"/>
                                            <xs:enumeration value="FISHINGROD"/>
                                            <xs:enumeration value="RAPIER"/>
                                            <xs:enumeration value="ANCIENTSWORD"/>
                                            <xs:enumeration value="CROSSBOW"/>
                                            <xs:enumeration value="FLAG"/>
                                            <xs:enumeration value="OWNTHING"/>
                                            <xs:enumeration value="DUALDAGGER"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="isWeaponMagic"  type="xs:boolean" default="false"/>
                                <xs:attribute name="isTwoHanded" type="xs:boolean" default="false"/>
                                <xs:attribute name="useShield" type="xs:boolean" default="false"/>
                                <xs:attribute name="shield" type="xs:string" default="SHIELD">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="SHIELD"/>
                                            <xs:enumeration value="SIGIL"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="giveAccessories" type="xs:boolean" default="true"/>
                                <xs:attribute name="raidBossAccessories" type="xs:boolean" default="false"/>
                                <xs:attribute name="SA" type="xs:string" default="NONE">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Acumen"/>
                                            <xs:enumeration value="Anger"/>
                                            <xs:enumeration value="Back Blow"/>
                                            <xs:enumeration value="Cheap Shot"/>
                                            <xs:enumeration value="Conversion"/>
                                            <xs:enumeration value="Critical Anger"/>
                                            <xs:enumeration value="Critical Bleed"/>
                                            <xs:enumeration value="Critical Damage"/>
                                            <xs:enumeration value="Critical Drain"/>
                                            <xs:enumeration value="Critical Poison"/>
                                            <xs:enumeration value="Critical Stun"/>
                                            <xs:enumeration value="Empower"/>
                                            <xs:enumeration value="Evasion"/>
                                            <xs:enumeration value="Focus"/>
                                            <xs:enumeration value="Guidance"/>
                                            <xs:enumeration value="Haste"/>
                                            <xs:enumeration value="Health"/>
                                            <xs:enumeration value="Long Blow"/>
                                            <xs:enumeration value="Magic Bless Body"/>
                                            <xs:enumeration value="Magic Chaos"/>
                                            <xs:enumeration value="Magic Damage"/>
                                            <xs:enumeration value="Magic Focus"/>
                                            <xs:enumeration value="Magic Hold"/>
                                            <xs:enumeration value="Magic Mental Shield"/>
                                            <xs:enumeration value="Magic Might"/>
                                            <xs:enumeration value="Magic Paralyze"/>
                                            <xs:enumeration value="Magic Poison"/>
                                            <xs:enumeration value="Magic Power"/>
                                            <xs:enumeration value="Magic Regeneration"/>
                                            <xs:enumeration value="Magic Shield"/>
                                            <xs:enumeration value="Magic Silence"/>
                                            <xs:enumeration value="Magic Weakness"/>
                                            <xs:enumeration value="Mana Up"/>
                                            <xs:enumeration value="Mental Shield"/>
                                            <xs:enumeration value="Might Mortal"/>
                                            <xs:enumeration value="Miser"/>
                                            <xs:enumeration value="Quick Recovery"/>
                                            <xs:enumeration value="Rsk. Evasion"/>
                                            <xs:enumeration value="Rsk. Focus"/>
                                            <xs:enumeration value="Rsk. Haste"/>
                                            <xs:enumeration value="Towering Blow"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== valanths1990/l2j-server-datapack/src/main/resources/data/autobots/armorset.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="armorset.xsd">
    <equipment classId="fighter" grade="NONE" setId="23" weaponType="SWORD"/>
    <equipment classId="warrior" grade="D" setId="58" weaponType="SWORD"/>
    <equipment classId="knight" grade="D" setId="58" weaponType="SWORD" useShield="true"/>
    <equipment classId="rogue" grade="D" setId="394" weaponType="SWORD"/>

    <equipment classId="mage" grade="NONE" setId="1101" weaponType="BLUNT" isWeaponMagic="true" useShield="true"/>
    <equipment classId="wizard" grade="D" setId="436" weaponType="BLUNT" isWeaponMagic="true" useShield="true"/>
    <equipment classId="cleric" grade="D" setId="436" weaponType="BLUNT" isWeaponMagic="true" useShield="true"/>

    <equipment classId="elvenFighter" grade="NONE" setId="23" weaponType="SWORD"/>
    <equipment classId="elvenKnight" grade="D" setId="58" weaponType="SWORD"/>
    <equipment classId="elvenScout" grade="D" setId="394" weaponType="BOW"/>

    <equipment classId="elvenMage" grade="NONE" setId="1101" weaponType="BLUNT" isWeaponMagic="true"
               useShield="true"/>
    <equipment classId="elvenWizard" grade="D" setId="436" weaponType="BLUNT" isWeaponMagic="true"
               useShield="true"/>
    <equipment classId="oracle" grade="D" setId="436" weaponType="BLUNT" isWeaponMagic="true" useShield="true"/>

    <equipment classId="darkFighter" grade="NONE" setId="23" weaponType="SWORD"/>
    <equipment classId="palusKnight" grade="D" setId="58" weaponType="SWORD" useShield="true"/>
    <equipment classId="assassin" grade="D" setId="394" weaponType="BOW"/>

    <equipment classId="darkMage" grade="NONE" setId="1101" weaponType="SWORD"/>
    <equipment classId="darkWizard" grade="D" setId="436" weaponType="BLUNT" isWeaponMagic="true"
               useShield="true"/>
    <equipment classId="shillienOracle" grade="D" setId="436" weaponType="BLUNT" isWeaponMagic="true"
               useShield="true"/>

    <equipment classId="orcFighter" grade="NONE" setId="23" weaponType="FIST"/>
    <equipment classId="orcRaider" grade="D" setId="58" weaponType="BLUNT"/>
    <equipment classId="orcMonk" grade="D" setId="58" weaponType="FIST"/>

    <equipment classId="orcMage" grade="NONE" setId="1101" weaponType="SWORD"/>
    <equipment classId="orcShaman" grade="D" setId="436" weaponType="BLUNT" isWeaponMagic="true"
               useShield="true"/>

    <equipment classId="dwarvenFighter" grade="NONE" setId="23" weaponType="SWORD"/>
    <equipment classId="artisan" grade="D" setId="58" weaponType="POLE"/>
    <equipment classId="scavenger" grade="D" setId="58" weaponType="POLE"/>

    <equipment classId="maleSoldier" grade="NONE" setId="23" weaponType="SWORD"/>
    <equipment classId="femaleSoldier" grade="NONE" setId="23" weaponType="SWORD"/>

    <equipment classId="trooper" grade="D" setId="394" weaponType="SWORD"/>
    <equipment classId="warder" grade="D" setId="394" weaponType="SWORD"/>


    <!-- Gladiator -->
    <equipment classId="gladiator" grade="C" setId="356" weaponType="DUAL"/>
    <equipment classId="gladiator" grade="B" setId="2381" weaponType="DUAL"/>
    <equipment classId="gladiator" grade="A" setId="10794" weaponType="DUAL"/>
    <equipment classId="duelist" grade="S" setId="10799" weaponType="DUAL" raidBossAccessories="true"/>

    <equipment classId="duelist" grade="S84" setId="16168" weaponType="DUAL" raidBossAccessories="true"/>

    <!-- Warlord -->
    <equipment classId="warlord" grade="C" setId="356" weaponType="POLE"/>
    <equipment classId="warlord" grade="B" setId="2381" weaponType="POLE"/>
    <equipment classId="warlord" grade="A" setId="10794" weaponType="POLE"/>
    <equipment classId="dreadnought" grade="S" setId="10799" weaponType="POLE" raidBossAccessories="true"/>

    <equipment classId="dreadnought" grade="S84" setId="16168" weaponType="POLE" raidBossAccessories="true"/>

    <!-- Paladin -->
    <equipment classId="paladin" grade="C" setId="356" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="paladin" grade="B" setId="2381" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="paladin" grade="A" setId="10794" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="phoenixKnight" grade="S" setId="10799" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>
    <equipment classId="phoenixKnight" grade="S84" setId="16171" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>

    <!-- Dark Avenger -->
    <equipment classId="darkAvenger" grade="C" setId="356" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="darkAvenger" grade="B" setId="2381" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="darkAvenger" grade="A" setId="10794" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="hellKnight" grade="S" setId="10799" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>
    <equipment classId="hellKnight" grade="S84" setId="16171" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>

    <!-- Treasure Hunter -->
    <equipment classId="treasureHunter" grade="C" setId="401" weaponType="DAGGER" SA="Focus"/>
    <equipment classId="treasureHunter" grade="B" setId="2391" weaponType="DAGGER" SA="Focus"/>
    <equipment classId="treasureHunter" grade="A" setId="10796" weaponType="DAGGER" SA="Focus"/>
    <equipment classId="adventurer" grade="S" setId="10800" weaponType="DAGGER" SA="Critical Damage"
               raidBossAccessories="true"/>
    <equipment classId="adventurer" grade="S84" setId="16172" weaponType="DAGGER" SA="Critical Damage"
               raidBossAccessories="true"/>

    <!-- Hawkeye -->
    <equipment classId="hawkeye" grade="C" setId="401" weaponType="BOW" SA="Evasion"/>
    <equipment classId="hawkeye" grade="B" setId="2391" weaponType="BOW" SA="Evasion"/>
    <equipment classId="hawkeye" grade="A" setId="10796" weaponType="BOW" SA="Focus"/>
    <equipment classId="sagittarius" grade="S" setId="10800" weaponType="BOW" SA="Focus"
               raidBossAccessories="true"/>
    <equipment classId="sagittarius" grade="S84" setId="16172" weaponType="BOW" SA="Focus"
               raidBossAccessories="true"/>

    <!-- Temple Knight -->
    <equipment classId="templeKnight" grade="C" setId="356" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="templeKnight" grade="B" setId="2381" weaponType="SWORD" useShield="true" SA="Focus"/>
    <equipment classId="templeKnight" grade="A" setId="10794" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="evaTemplar" grade="S" setId="10799" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>
    <equipment classId="evaTemplar" grade="S84" setId="16171" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>

    <!-- Sword Singer -->
    <equipment classId="swordSinger" grade="C" setId="356" weaponType="DUAL"/>
    <equipment classId="swordSinger" grade="B" setId="2381" weaponType="DUAL"/>
    <equipment classId="swordSinger" grade="A" setId="10794" weaponType="DUAL"/>
    <equipment classId="swordMuse" grade="S" setId="10799" weaponType="DUAL" raidBossAccessories="true"/>

    <equipment classId="swordMuse" grade="S84" setId="16171" weaponType="DUAL" raidBossAccessories="true"/>

    <!-- Plains Walker -->
    <equipment classId="plainsWalker" grade="C" setId="401" weaponType="DAGGER" SA="Focus"/>
    <equipment classId="plainsWalker" grade="B" setId="2391" weaponType="DAGGER" SA="Focus"/>
    <equipment classId="plainsWalker" grade="A" setId="10796" weaponType="DAGGER" SA="Focus"/>
    <equipment classId="windRider" grade="S" setId="10800" weaponType="DAGGER" SA="Critical Damage"
               raidBossAccessories="true"/>
    <equipment classId="windRider" grade="S84" setId="16172" weaponType="DAGGER" SA="Critical Damage"
               raidBossAccessories="true"/>

    <!-- Silver Ranger -->
    <equipment classId="silverRanger" grade="C" setId="401" weaponType="BOW" SA="Evasion"/>
    <equipment classId="silverRanger" grade="B" setId="2391" weaponType="BOW" SA="Evasion"/>
    <equipment classId="silverRanger" grade="A" setId="10796" weaponType="BOW" SA="Focus"/>
    <equipment classId="moonlightSentinel" grade="S" setId="10800" weaponType="BOW" SA="Focus"
               raidBossAccessories="true"/>
    <equipment classId="moonlightSentinel" grade="S84" setId="16172" weaponType="BOW" SA="Focus"
               raidBossAccessories="true"/>

    <!-- Shillien Knight -->
    <equipment classId="shillienKnight" grade="C" setId="356" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="shillienKnight" grade="B" setId="2381" weaponType="SWORD" useShield="true" SA="Focus"/>
    <equipment classId="shillienKnight" grade="A" setId="10794" weaponType="SWORD" useShield="true" SA="Health"/>
    <equipment classId="shillienTemplar" grade="S" setId="10799" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>
    <equipment classId="shillienTemplar" grade="S84" setId="16171" weaponType="SWORD" useShield="true" SA="Health"
               raidBossAccessories="true"/>

    <!-- Blade Dancer -->
    <equipment classId="bladedancer" grade="C" setId="356" weaponType="DUAL"/>
    <equipment classId="bladedancer" grade="B" setId="2381" weaponType="DUAL"/>
    <equipment classId="bladedancer" grade="A" setId="10794" weaponType="DUAL"/>
    <equipment classId="spectralDancer" grade="S" setId="10799" weaponType="DUAL" raidBossAccessories="true"/>

    <equipment classId="spectralDancer" grade="S84" setId="16171" weaponType="DUAL" raidBossAccessories="true"/>

    <!-- Abyss Walker -->
