=== valanths1990/l2j-server-datapack/src/main/resources/data/xsd/spawnlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="spawn" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="AIData" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:nonNegativeInteger" name="aggroRange" minOccurs="0" />
										<xs:element type="xs:boolean" name="disableRandomAnimation" minOccurs="0" />
										<xs:element type="xs:boolean" name="disableRandomWalk" minOccurs="0" />
										<xs:element type="xs:integer" name="fleeX" minOccurs="0" />
										<xs:element type="xs:integer" name="fleeY" minOccurs="0" />
										<xs:element type="xs:integer" name="fleeZ" minOccurs="0" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="npc" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="id" type="xs:positiveInteger" use="required" />
											<xs:attribute name="x" type="xs:integer" />
											<xs:attribute name="y" type="xs:integer" />
											<xs:attribute name="z" type="xs:integer" />
											<xs:attribute name="heading" type="xs:integer" />
											<xs:attribute name="count" type="xs:positiveInteger" />
											<xs:attribute name="respawnDelay" type="xs:nonNegativeInteger" />
											<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" />
											<xs:attribute name="periodOfDay">
												<xs:simpleType>
													<xs:restriction base="xs:token">
														<xs:enumeration value="day" />
														<xs:enumeration value="night" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" />
						<xs:attribute type="xs:string" name="zone" />
						<xs:attribute type="xs:boolean" name="enabled" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
	</xs:complexType>
	</xs:element>
</xs:schema>

=== valanths1990/l2j-server-datapack/src/main/resources/data/custom/farmzone/custom/chromatichighland.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../xsd/spawnlist.xsd">
    <!-- oren22_2219_a01 -->
    <spawn name="Chromatic" zone="Chromatic Highland" enabled="false">
        <AIData>
            <disableRandomAnimation>false</disableRandomAnimation>
            <disableRandomWalk>false</disableRandomWalk>
        </AIData>
        <npc id="22267" x="148829" y="160012" z="-3147" heading="51141" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="149199" y="160169" z="-3160" heading="1636" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="149363" y="159592" z="-3203" heading="51219" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="149833" y="159550" z="-3206" heading="65341" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="149973" y="159024" z="-3239" heading="52635" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="150410" y="158974" z="-3264" heading="58980" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="150438" y="158538" z="-3289" heading="47817" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="150887" y="158541" z="-3346" heading="1503" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="150910" y="158538" z="-3358" heading="15788" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="150885" y="157953" z="-3370" heading="57820" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="151383" y="158401" z="-3400" heading="13416" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="151377" y="157784" z="-3376" heading="2294" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="151926" y="158265" z="-3417" heading="8841" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="151950" y="157592" z="-3384" heading="47093" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="152641" y="158121" z="-3456" heading="5942" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="153206" y="157880" z="-3456" heading="59121" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="152425" y="157089" z="-3511" heading="34115" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="153167" y="156829" z="-3623" heading="58702" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="153250" y="156208" z="-3667" heading="50453" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="153389" y="155776" z="-3673" heading="57286" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="153259" y="155151" z="-3645" heading="48690" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="152982" y="154651" z="-3646" heading="40443" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="152601" y="154317" z="-3668" heading="40312" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="152236" y="154032" z="-3673" heading="39596" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="151741" y="153963" z="-3665" heading="32859" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="151410" y="154237" z="-3671" heading="28186" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="150922" y="154334" z="-3663" heading="28244" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="150675" y="154650" z="-3649" heading="18430" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="151028" y="155391" z="-3673" heading="10598" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="151423" y="155765" z="-3673" heading="7615" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="152018" y="156095" z="-3675" heading="4613" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="152606" y="155882" z="-3681" heading="59222" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="152145" y="155285" z="-3679" heading="31678" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="151541" y="155047" z="-3676" heading="42763" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="153173" y="153723" z="-3653" heading="55497" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="153739" y="153294" z="-3654" heading="58905" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="153974" y="153626" z="-3669" heading="738" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="154566" y="153481" z="-3666" heading="64880" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="154993" y="153110" z="-3661" heading="52017" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="154521" y="152407" z="-3649" heading="43712" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="154241" y="151884" z="-3626" heading="38884" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="153814" y="151574" z="-3553" heading="35411" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="154539" y="151333" z="-3608" heading="2183" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="155078" y="151744" z="-3710" heading="745" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="155455" y="151616" z="-3702" heading="59396" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="155879" y="150949" z="-3688" heading="54094" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="156031" y="150402" z="-3683" heading="49958" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="156038" y="150023" z="-3670" heading="49801" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="156165" y="149558" z="-3648" heading="61923" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="156554" y="149621" z="-3629" heading="10146" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="156572" y="150141" z="-3630" heading="20744" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="156407" y="150526" z="-3641" heading="21082" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="156187" y="151072" z="-3662" heading="19216" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="155915" y="151582" z="-3655" heading="14260" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="156034" y="152151" z="-3636" heading="15252" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="156223" y="152608" z="-3600" heading="9802" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="156580" y="152804" z="-3567" heading="4410" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="156791" y="153193" z="-3518" heading="13818" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="157177" y="153066" z="-3520" heading="63817" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="157622" y="153158" z="-3507" heading="3096" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="157992" y="153344" z="-3443" heading="5070" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="157898" y="152067" z="-3416" heading="44394" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="157540" y="151458" z="-3400" heading="43481" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="157202" y="150997" z="-3552" heading="42081" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="157173" y="150522" z="-3512" heading="51712" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="156898" y="150185" z="-3550" heading="36746" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="156997" y="149099" z="-3599" heading="50934" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="157206" y="148455" z="-3574" heading="56355" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="157041" y="147924" z="-3600" heading="44729" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="156347" y="147781" z="-3726" heading="32570" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="155832" y="148773" z="-3698" heading="17011" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22264" x="155849" y="149484" z="-3709" heading="16444" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="157240" y="151947" z="-3534" heading="451" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22263" x="158353" y="152044" z="-3401" heading="64014" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="158792" y="151910" z="-3349" heading="62114" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="159275" y="151669" z="-3313" heading="59085" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22267" x="159762" y="151730" z="-3330" heading="1647" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="160259" y="151698" z="-3363" heading="64507" count="1" respawnDelay="60" respawnRandom="30"/>
        <npc id="22265" x="160708" y="151769" z="-3405" heading="3592" count="1" respawnDelay="60" respawnRandom="30"/>
